### ISSUE TITLE
How to pick dependency?

### ISSUE THREAD

**Issue by uetkaje** [tsgautier/node-majic#1]
How to pick dependency that will be injected, if the files duplicate with same name?

In example;

``` javascript
//./src/main/config.js
module.exports = {
    "greeting": "Hello World!"
}
```

``` javascript
//./src/lib/config.js
module.exports = {
    "greeting": "Hello world - lib"
}
```

``` javascript
//./src/main/helloworld.js
module.exports = function (config) {
    console.log(config.greeting);
}
```

**Comment by tsgautier** [comment]
The intent is to have unique names that are only dependent on the file name and explicitly not on the location. 

So I would discourage you from doing what you are doing. 

What would be your use case for having the same name?

**Comment by tsgautier** [comment]
@uetkaje do you have a specific suggestion or requirement that needs to be met?  If not I will close this issue.

**Comment by uetkaje** [comment]
I've totally misunderstood.
